process.env.NODE_ENV ??= "test";
process.env.PORT ??= "4001";
process.env.MONGO_URL ??=
  "mongodb://127.0.0.1:27018/mentorme_nest_test?replicaSet=rs0";
process.env.JWT_SECRET ??= "nest-test-secret-with-enough-length";
process.env.CORS_ORIGINS ??= "http://localhost:5173";
process.env.VNPAY_HASH_SECRET ??= "test-vnpay-hash-secret";
process.env.VNPAY_TMN_CODE ??= "TEST_TMN_CODE";
process.env.VNPAY_ENABLED ??= "true";
process.env.MOMO_SECRET_KEY ??= "test-momo-secret";
process.env.MOMO_ACCESS_KEY ??= "test-momo-access";
process.env.MOMO_PARTNER_CODE ??= "TEST_MOMO";
process.env.MOMO_ENABLED ??= "true";
process.env.SITE_ADMIN_EMAIL ??= "test-site-admin@example.com";
process.env.SITE_ADMIN_PASSWORD ??= "TestPassword1!";
process.env.SITE_ADMIN_FIRST_NAME ??= "Test";
process.env.SITE_ADMIN_LAST_NAME ??= "Administrator";
